#! /bin/sh

tmux has-session -t the-band-changed
if [ $? != 0 ]
then
    tmux new-session -s the-band-changed -n Server -d

    # create moar windows
    tmux new-window -t the-band-changed:1 -n Client
    tmux new-window -t the-band-changed:2 -n TestClient
    tmux new-window -t the-band-changed:3 -n TestServer
    tmux new-window -t the-band-changed:4 -n Zsh

    # run the server in the first window
    tmux send-keys -t the-band-changed:0.0 'cd ~/dev/the-band-changed && npm run server' C-m

    # run the client in the second window
    tmux send-keys -t the-band-changed:1.0 'cd ~/dev/the-band-changed && npm start' C-m

    # run the client tests in the third window
    tmux send-keys -t the-band-changed:2.0 'cd ~/dev/the-band-changed && npm run test:client' C-m

    # run the server tests in the fourth window
    tmux send-keys -t the-band-changed:3.0 'cd ~/dev/the-band-changed && npm run test:server' C-m

    # just get to the proper path in the last window
    tmux send-keys -t the-band-changed:4.0 'cd ~/dev/the-band-changed' C-m

    # select the server window and pane
    tmux select-window -t the-band-changed:0.0
fi
tmux attach -t the-band-changed
