#! /bin/sh

tmux has-session -t thebandchanged
if [ $? != 0 ]
then
    tmux new-session -s thebandchanged -n Server -d

    # create moar windows
    tmux new-window -t thebandchanged:1 -n Client
    tmux new-window -t thebandchanged:2 -n TestClient
    tmux new-window -t thebandchanged:3 -n TestServer
    tmux new-window -t thebandchanged:4 -n Zsh

    # run the server in the first window
    tmux send-keys -t thebandchanged:0.0 'cd ~/dev/thebandchanged && npm run server' C-m

    # run the client in the second window
    tmux send-keys -t thebandchanged:1.0 'cd ~/dev/thebandchanged && npm start' C-m

    # run the client tests in the third window
    tmux send-keys -t thebandchanged:2.0 'cd ~/dev/thebandchanged && npm run test:client' C-m

    # run the server tests in the fourth window
    tmux send-keys -t thebandchanged:3.0 'cd ~/dev/thebandchanged && npm run test:server' C-m

    # just get to the proper path in the last window
    tmux send-keys -t thebandchanged:4.0 'cd ~/dev/thebandchanged' C-m

    # select the server window and pane
    tmux select-window -t thebandchanged:0.0
fi
tmux attach -t thebandchanged
